### ISSUE TITLE
[Maintenance] Setup Discussions Board

### ISSUE THREAD

**Issue by xames3** [ciesin-geospatial/TOPSTSCHOOL-SPHINX#5]
- this issue is quite straightforward and the deliverables would be as follows:

  - [x] setting up a relatively native discussions board with proper labels, categories and sections.
  - [x] setting up a dedicated feedback section or category for recording all the feedbacks related to the documentation.

it'd be a good idea to mention all the active contributors and core development team in an announcement post.

**Comment by xames3** [comment]
- added a discussions board with respective sections and categories. this issue is good to close after a quick testing.

**Comment by xames3** [comment]
@jfmartinez4, please check if the feedback capturing workflow is acceptable or not. open the documentation [here](https://ciesin-geospatial.github.io/TOPSTSCHOOL-SPHINX/) and check the bottom of the page where it says Feedback.

![Image](https://github.com/user-attachments/assets/612fb907-6b53-4d2a-9f27-1ad68ead8682)

like the OSDMP site, it takes you to a discussion board where the user can provide feedbacks. I've made a dedicated section and category for gathering all community feedbacks. you can check it out [here](https://github.com/ciesin-geospatial/TOPSTSCHOOL-SPHINX/discussions). if this looks okay, close this issue. I had added this way before our meeting.

**Comment by jfmartinez4** [comment]
@xames3 just sent you a test feeedback.

**Comment by xames3** [comment]
@jfmartinez4, does it work according to what you were expecting for recording user feedbacks? if so, do let me know and close the issue. if something else needs to be addressed, share those thoughts too. I shall try to incorporate them at earliest.

**Comment by jfmartinez4** [comment]
Just tested the tool again and it looks great to start with! Be careful with adding too many labels and getting cluttered.
